GET http://localhost:4000/users/64de6c67164419785359bc52

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "email": "bnbfffnb@sggg.com",
    "password": "StrongPass123"
}
###
POST http://localhost:4000/feed
Content-Type: application/json

{
    "title": "Bloomood's Beginner Picks: Effortless Elegance for Every Home",
    "description": "New to the world of plants? Bloomood has curated a collection of beginner-friendly plants that will grace your home with elegance and charm. These low-maintenance wonders are perfect for those taking their first steps into the green realm. Elevate your space with these easy-care companions!",
    "imageUrl":"https://bloomoodimg.s3.eu-north-1.amazonaws.com/plant-removebg-preview.png"
}
### 
GET http://localhost:4000/feed