GET http://localhost:4000/users/64de6c67164419785359bc52

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "email": "bnbfffnb@sggg.com",
    "password": "StrongPass123"
}
###
POST http://localhost:4000/feed
Content-Type: application/json

{
    "title": "Bloomood's Beginner Picks: Effortless Elegance for Every Home",
    "description": "New to the world of plants? Bloomood has curated a collection of beginner-friendly plants that will grace your home with elegance and charm. These low-maintenance wonders are perfect for those taking their first steps into the green realm. Elevate your space with these easy-care companions!",
    "imageUrl":"https://bloomoodimg.s3.eu-north-1.amazonaws.com/plant-removebg-preview.png"
}
### 
GET http://localhost:4000/feed


###
POST http://localhost:4000/storeItem
Content-Type: application/json

{
    "name": "Kalanchoe",
    "latinName":"Kalanchoe spp.",
    "description": "Kalanchoes are succulents with vibrant flowers and fleshy leaves. They thrive in bright light conditions.",
    "price":15.95,
    "imageUrl":"https://bloomoodimg.s3.eu-north-1.amazonaws.com/storeItems/Kalanchoe-fotor-bg-remover-20230830131830.png",
    "category": "bright-light"
}
###
GET http://localhost:4000/storeItem?category=bumblebee
Content-Type: application/json